# SPDX-License-Identifier: GPL-2.0
# NEON-accelerated encoding requires CONFIG_KERNEL_MODE_NEON=y
obj-$(CONFIG_LZ4KDR_COMPRESS) += lz4kdr_encode.o lz4kdr_neon.o
obj-$(CONFIG_LZ4KDR_DECOMPRESS) += lz4kdr_decode.o